GET HTTP://127.0.0.1:2222/test_token
Content-Type: application/json
# Authorization: Token 9b2f7421ef0008255a33832a4d0bb276d816fe44
Authorization: Token 6827a2c107a043b18a0fe7db6465e75bd72ec8d3

###

POST HTTP://127.0.0.1:2222/login
Content-Type: application/json

{ "username": "doctor2", "password": "1234"}


###

POST HTTP://127.0.0.1:2222/signup
Content-Type: application/json
Authorization: Token 425525c02ad1207feab9eece4e7472e831e8d170
# Authorization: Token a409320b6b40f90b622320cc0ba38cc4a5695528



{
    "username": "p2d2",
    "password": "1234",
    "email": "p2d2@lazyeyegame.com",
    "role": 3,
    "firstname": "dd",
    "lastname": "dsda"
}


###

GET HTTP://127.0.0.1:2222/doctor/patients
Content-Type: application/json
Authorization: Token 425525c02ad1207feab9eece4e7472e831e8d170
###

PATCH HTTP://127.0.0.1:2222/doctor/patient/10
Content-Type: application/json
Authorization: Token 425525c02ad1207feab9eece4e7472e831e8d170

{
    "firstname": "edited",
    "gender": "female",
    "location": "america"
}

###


PATCH HTTP://127.0.0.1:2222/editgame/game/tetris/patient/11
Content-Type: application/json
Authorization: Token 425525c02ad1207feab9eece4e7472e831e8d170

{
    "color": "blue",
    "level": 2
}

###



