# Generated by Django 4.2.5 on 2023-09-18 19:27

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('tenant_name', models.CharField(max_length=100, unique=True)),
                ('tenant_uuid', models.UUIDField(default=uuid.uuid4)),
                ('paid_until', models.DateField(null=True)),
                ('on_trial', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('domain_url', models.URLField(blank=True, default='localhost', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
