# Generated by Django 4.2.5 on 2023-09-13 20:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='invalid username format', regex='^[a-z0-9+]{2,25}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
