# Generated by Django 4.2.5 on 2023-09-26 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacmandata',
            name='highscore',
        ),
        migrations.RemoveField(
            model_name='pacmandata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='pacmandata',
            name='playtime',
        ),
        migrations.RemoveField(
            model_name='rollexdata',
            name='highscore',
        ),
        migrations.RemoveField(
            model_name='rollexdata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='rollexdata',
            name='playtime',
        ),
        migrations.RemoveField(
            model_name='tetrisdata',
            name='highscore',
        ),
        migrations.RemoveField(
            model_name='tetrisdata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='tetrisdata',
            name='playtime',
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highscore', models.PositiveIntegerField(default=0)),
                ('playtime', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
