# Generated by Django 4.2.5 on 2023-10-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_pacmandata_highscore_remove_pacmandata_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='highscore',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='playtime',
            field=models.CharField(default=''),
        ),
    ]
